---
title: "Response to R Westbrook"
format: html
---

FIRST, let's begin with the recent results of the FY24-FY25 audited financial statements.

Last board meeting Mr Westbrook asked several pointed questions, presumably to put to rest once and for all certain controversies about the General Fund operations for that year:

Did the city's General Fund operate at a deficit in the fiscal year? CORRECT ANSWER = NO

Did the city dip into its General Fund reserves in that fiscal year? CORRECT ANSWER = NO

Uncharacteristically, Mr. Westbrook left off the most important question:

Did the city avoid operating the General Fund at a deficit, and avoid dipping into the reserves, due to conservative and careful budgeting and spending practices, OR   

was the city just plain LUCKY to have the Sales Tax windfall in that year, coupled with a paper accounting adjustment of nearly $2,000,000 boosting reserve levels?

CORRECT ANSWER = JUST PLAIN LUCKY; NO CONSERVATIVE, CAREFUL PLANNING BY THE COUNCIL (OR ANYONE ELSE) WAS INVOLVED.

Mr. Macaluso was the only member to then ask what the results WOULD HAVE BEEN been without the Sales Tax windfall.  Even though staff answered truthfully, no one had the chutzpah to say the implication out loud: 

YES, it had been a matter of dumb luck that the city was NOT operating the General Fund at a deficit and eating into reserves.

So, I certainly would not rush to pat myself or others on the back about what fine financial care the city council is providing in the General Fund.  Just admit that you were lucky; AND don't be indignant when taxpayers ask why a deficit budget was passed in the first place.  

One bright spot is the accuracy with which staff projected the expected deficit and its affect on the reserves.  Take away those two windfall events and they hit the projections almost perfectly - KUDOS TO THEM. 

----
